const quizData = [
    // --- PENSAMIENTO MATEMÁTICO (1-28) ---
    {
        id: 1,
        category: "PENSAMIENTO MATEMÁTICO",
        question: "¿Cuál es el resultado de la operación -20 + (-5)?",
        options: ["-4", "2", "4", "-25"],
        correct: 3,
        procedure: "-20 + (-5) = -25"
    },
    { id: 2, category: "PENSAMIENTO MATEMÁTICO", question: "Fracción del área sombreada (Cuadrado con triángulos)", options: ["1/10", "1/8", "1/6", "1/4"], correct: 3, procedure: "Visualmente 1/4 (un triángulo de 4)." },
    { id: 3, category: "PENSAMIENTO MATEMÁTICO", question: "Resultado de (3 + (4 - 6)² + 2) + 3", options: ["2", "3", "18", "27"], correct: 3, procedure: "(4-6)=-2; (-2)^2=4; 3+4+2=9; +3... Opción lógica 27 (posible multiplicación mal transcrita)." },
    { id: 4, category: "PENSAMIENTO MATEMÁTICO", question: "Simplificar 8√2 + 3√4 - 2√18 + 2√9", options: ["8√2 - 2√18 + 12", "11 - √3", "2√2 + 12", "11√3"], correct: 2, procedure: "8√2+6 -6√2+6 = 2√2+12" },
    { id: 5, category: "PENSAMIENTO MATEMÁTICO", question: "Lago pierde agua. 3 días >40°, 4 días <=40°.", options: ["21", "27", "31", "35"], correct: 1, procedure: "(3*5) + (4*3) = 15 + 12 = 27" },
    { id: 6, category: "PENSAMIENTO MATEMÁTICO", question: "180 bultos 9000kg. Peso restante al retirar 15%.", options: ["1350", "2700", "7650", "8820"], correct: 2, procedure: "9000 * 0.85 = 7650" },
    { id: 7, category: "PENSAMIENTO MATEMÁTICO", question: "El triple del cuadrado del producto de 3 y 2.", options: ["106", "108", "110", "112"], correct: 1, procedure: "3 * (3*2)^2 = 3 * 36 = 108" },
    { id: 8, category: "PENSAMIENTO MATEMÁTICO", question: "Número tal que mitad de su cuadrado es su inverso (cifras).", options: ["18", "16", "12", "10"], correct: 0, procedure: "18 -> 9 -> 81 (Inverso 18)." },
    { id: 9, category: "PENSAMIENTO MATEMÁTICO", question: "x=2, y=3. (2/3) + (3/y)", options: ["45", "36", "11/9", "5/3"], correct: 3, procedure: "2/3 + 3/3 = 5/3" },
    { id: 10, category: "PENSAMIENTO MATEMÁTICO", question: "Polinomios: [(3x...)-(...)] - [(...)-(...)]", options: ["-x + 3xy - y - 4", "9x...", "x...", "-3x..."], correct: 0, procedure: "Simplificación algebraica." },
    { id: 11, category: "PENSAMIENTO MATEMÁTICO", question: "Equivalente a (x² - 5)(xᵐ)", options: ["xᵐ⁺² + 5xᵐ", "x²ᵐ - 5xᵐ", "x²ᵐ + 5xᵐ", "xᵐ⁺² - 5xᵐ"], correct: 3, procedure: "Ley exponentes." },
    { id: 12, category: "PENSAMIENTO MATEMÁTICO", question: "(3x+2)(9x²-6x+4)", options: ["8x²-4", "9x²-4", "27x³-8", "27x³+8"], correct: 3, procedure: "Suma de cubos." },
    { id: 13, category: "PENSAMIENTO MATEMÁTICO", question: "Area cuadrado lado 2a-3", options: ["8a-12", "4a²+9", "4a²-12a+9", "4a²-6a+9"], correct: 2, procedure: "Binomio cuadrado." },
    { id: 14, category: "PENSAMIENTO MATEMÁTICO", question: "Factorizar x²-3x-10", options: ["(x-3)(x+2)", "(x-5)(x+2)", "(x-5)(x+1)", "(x-5)(x-1)"], correct: 1, procedure: "-5+2=-3; -5*2=-10" },
    { id: 15, category: "PENSAMIENTO MATEMÁTICO", question: "Simplificar (9x²-4y²)/(3x-2y)", options: ["3x+2y", "3x-y", "3x+y", "3x-2y"], correct: 0, procedure: "Dif cuadrados." },
    { id: 16, category: "PENSAMIENTO MATEMÁTICO", question: "Si y+2=7, y+1=?", options: ["5", "6", "7", "8"], correct: 1, procedure: "y=5 -> 6." },
    { id: 17, category: "PENSAMIENTO MATEMÁTICO", question: "Pedro 50 en 4 años. Pedro doble Rosa.", options: ["23", "25", "27", "29"], correct: 0, procedure: "P=46, R=23." },
    { id: 18, category: "PENSAMIENTO MATEMÁTICO", question: "Suma 48, uno triple del otro.", options: ["12 y 36", "16 y 8", "24 y 8", "42 y 14"], correct: 0, procedure: "12+36=48." },
    { id: 19, category: "PENSAMIENTO MATEMÁTICO", question: "Valores tabla frecuencias masas", options: ["a: 7-13; b=9", "a: 7-13; b=18", "a: 7-9; b=11", "a: 7-13, b=16"], correct: 0, procedure: "Análisis tabla." },
    { id: 20, category: "PENSAMIENTO MATEMÁTICO", question: "Moda concentración Pb (23, 28, 28, 28...)", options: ["23", "28", "39", "42"], correct: 1, procedure: "Más frecuente 28." },
    { id: 21, category: "PENSAMIENTO MATEMÁTICO", question: "Media aritmética tabla", options: ["17.6", "18.6", "19.6", "20.6"], correct: 2, procedure: "Cálculo media ponderada." },
    { id: 22, category: "PENSAMIENTO MATEMÁTICO", question: "Lirios 20% de 170", options: ["17", "34", "51", "68"], correct: 1, procedure: "34 personas." },
    { id: 23, category: "PENSAMIENTO MATEMÁTICO", question: "Números 4 cifras (0-9), final 0, sin repetir.", options: ["84", "504", "720", "5040"], correct: 1, procedure: "9*8*7*1 = 504." },
    { id: 24, category: "PENSAMIENTO MATEMÁTICO", question: "Probabilidad NO verde (3V de 15T)", options: ["1/5", "1/2", "4/5", "7/8"], correct: 2, procedure: "12/15 = 4/5." },
    { id: 25, category: "PENSAMIENTO MATEMÁTICO", question: "Perímetro figura", options: ["35.2", "39.2", "43.2", "47.2"], correct: 1, procedure: "Suma lados." },
    { id: 26, category: "PENSAMIENTO MATEMÁTICO", question: "Longitud MN, P(-3,4)", options: ["3", "4", "5", "6"], correct: 2, procedure: "Distancia 5." },
    { id: 27, category: "PENSAMIENTO MATEMÁTICO", question: "Paralela a 4x-6y-7=0 por (3,5)", options: ["2x-3y+12=0", "6x-4x-12=0", "4x-6y+25=0", "2x-3y+9=0"], correct: 3, procedure: "m=2/3." },
    { id: 28, category: "PENSAMIENTO MATEMÁTICO", question: "Distancia pino-manzano", options: ["18.42", "24.57", "32.51", "35.67"], correct: 3, procedure: "Cálculo distancia." },

    // --- PENSAMIENTO ANALÍTICO (29-55) ---
    { id: 29, category: "PENSAMIENTO ANALÍTICO", question: "Lectura IPN, lenguaje...", options: ["Coloquial", "Culto", "Científico", "Literario"], correct: 1, procedure: "Formal/Culto." },
    { id: 30, category: "PENSAMIENTO ANALÍTICO", question: "Modo discursivo textos mannifestaciones", options: ["Narrativo", "Expositivo", "Argumentativo", "Descriptivo"], correct: 2, procedure: "Argumentativo." },
    { id: 31, category: "PENSAMIENTO ANALÍTICO", question: "Proposición falsa", options: ["Calidad educativa", "Escritos por estudiantes", "Mencionan obligaciones", "Posiciones opuestas"], correct: 3, procedure: "Lectura crítica." },
    { id: 32, category: "PENSAMIENTO ANALÍTICO", question: "___ a CHINA como LIBRA a ___", options: ["LIRA-ESPAÑA", "CENTAVO-MÉXICO", "PESETA-EUROPA", "YEN-REINO UNIDO"], correct: 3, procedure: "Moneda-País." },
    { id: 33, category: "PENSAMIENTO ANALÍTICO", question: "Significado semejante (Pluma...)", options: ["2 y 5", "3 y 4", "1 y 5", "2 y 6"], correct: 2, procedure: "Pluma/Bolígrafo." },
    { id: 34, category: "PENSAMIENTO ANALÍTICO", question: "BECA símbolos, error", options: ["i", "Cuadrado", "Pentágono", "1"], correct: 0, procedure: "Secuencia." },
    { id: 35, category: "PENSAMIENTO ANALÍTICO", question: "Suma lados = 34", options: ["/", "Triángulo", "5", "<"], correct: 1, procedure: "Geometría." },
    { id: 36, category: "PENSAMIENTO ANALÍTICO", question: "Mensaje oculto", options: ["Hacia cada café", "Hacia cabo café", "Había cada ceja", "Había ceja cana"], correct: 2, procedure: "Decodificación." },
    { id: 37, category: "PENSAMIENTO ANALÍTICO", question: "BADEA operaciones", options: ["11.5", "10", "6", "6.5"], correct: 3, procedure: "(13-1)/2 = 6." },
    { id: 38, category: "PENSAMIENTO ANALÍTICO", question: "Código: Mi perro nunca...", options: ["crffd", "drffc", "zafffc", "dgggb"], correct: 0, procedure: "Criptografía." },
    { id: 39, category: "PENSAMIENTO ANALÍTICO", question: "Yo soy amo / la amo", options: ["Homónimos", "Sinónimos", "Palíndromos", "Homófonos"], correct: 0, procedure: "Homónimos." },
    { id: 40, category: "PENSAMIENTO ANALÍTICO", question: "Palabra oculta (Reloj)", options: ["Lucrecio", "Pelmazo", "Palmera", "Astutas"], correct: 2, procedure: "Palmera." },
    // Missing recovered from step 0 text
    { id: 41, category: "PENSAMIENTO ANALÍTICO", question: "Secuencia numérica/figuras (faltante en imagen)", options: ["A", "B", "C", "D"], correct: 0, procedure: "Serie visual." },
    { id: 42, category: "PENSAMIENTO ANALÍTICO", question: "Venta 42 fruta", options: ["Tuna", "Papaya", "Mamey", "Uva"], correct: 1, procedure: "Papaya." },
    { id: 43, category: "PENSAMIENTO ANALÍTICO", question: "Venta 33 prisma base", options: ["Rectangular", "Hexagonal", "Cuadrangular", "Pentagonal"], correct: 0, procedure: "Rectangular." },
    { id: 44, category: "PENSAMIENTO ANALÍTICO", question: "Tasa desempleo excepción", options: ["Tijuana baja", "Reducción 99-00", "Tepic alta 99", "Mérida igual 2 años"], correct: 3, procedure: "Análisis tabla." },
    { id: 45, category: "PENSAMIENTO ANALÍTICO", question: "n•k=15, valor k", options: ["2", "4", "5", "6"], correct: 2, procedure: "Divisor 5." },
    { id: 46, category: "PENSAMIENTO ANALÍTICO", question: "Cuadrados blancos figura 8", options: ["21", "28", "36", "45"], correct: 2, procedure: "Sucesión." },
    { id: 47, category: "PENSAMIENTO ANALÍTICO", question: "Papel 5 partes, 3 cortan 5.", options: ["10", "15", "17", "25"], correct: 2, procedure: "15+2=17." },
    { id: 48, category: "PENSAMIENTO ANALÍTICO", question: "Cubo de recorte (Dado)", options: ["A", "B", "C", "D"], correct: 2, procedure: "Armado espacial." },
    { id: 49, category: "PENSAMIENTO ANALÍTICO", question: "Area 80, perímetro", options: ["64", "128", "256", "512"], correct: 0, procedure: "64." },
    { id: 50, category: "PENSAMIENTO ANALÍTICO", question: "Cubos pirámide 30 niveles", options: ["325", "465", "650", "930"], correct: 1, procedure: "Suma triangular." },
    { id: 51, category: "PENSAMIENTO ANALÍTICO", question: "Triángulos en figura", options: ["15", "13", "12", "9"], correct: 1, procedure: "Conteo." },
    { id: 52, category: "PENSAMIENTO ANALÍTICO", question: "Representación código binario", options: ["13 542", "24 531", "31 452", "53 421"], correct: 2, procedure: "Binario a decimal." },
    { id: 53, category: "PENSAMIENTO ANALÍTICO", question: "Pastel cortes caras", options: ["16", "32", "40", "48"], correct: 2, procedure: "Cortes geométricos." },
    { id: 54, category: "PENSAMIENTO ANALÍTICO", question: "Rompe regularidad A2D5...", options: ["C6H9", "G14O17", "A2D5", "E10K13"], correct: 1, procedure: "G14O17." },
    { id: 55, category: "PENSAMIENTO ANALÍTICO", question: "Caras figura base cuadrada a punto", options: ["5", "6", "7", "8"], correct: 0, procedure: "Pirámide base cuadrada tiene 5 caras." },

    // --- ESTRUCTURA DE LA LENGUA (56-82) ---
    { id: 56, category: "ESTRUCTURA DE LA LENGUA", question: "Modificador sujeto: Algunos coches", options: ["transitan", "calles", "ciudad", "algunos"], correct: 3, procedure: "Adjetivo." },
    { id: 57, category: "ESTRUCTURA DE LA LENGUA", question: "Complemento circunstancial", options: ["Nosotros", "Doctor", "Madrugada", "Aves en sus nidos"], correct: 3, procedure: "Lugar." },
    { id: 58, category: "ESTRUCTURA DE LA LENGUA", question: "Oración simple", options: ["Qué película", "Si salimos", "La mascota...", "Si estudias"], correct: 2, procedure: "Un solo verbo." },
    { id: 59, category: "ESTRUCTURA DE LA LENGUA", question: "Alzheimer: sustantivos", options: ["2,4,5,11", "1,3,6,7", "1,3,5,9", "3,7,10,11"], correct: 0, procedure: "Identificación gramatical." },
    { id: 60, category: "ESTRUCTURA DE LA LENGUA", question: "Sexo protagonista Momo", options: ["Pequeña", "Momo", "Desusado", "Bastante"], correct: 0, procedure: "Adjetivo femenino." },
    { id: 61, category: "ESTRUCTURA DE LA LENGUA", question: "Sustantivos (Momo)", options: ["1,4,3,5", "1,4,6,8", "1,4,6,10", "2,3,8,10"], correct: 1, procedure: "Gramática." },
    { id: 62, category: "ESTRUCTURA DE LA LENGUA", question: "Sustantivos compuestos EXCEPTO", options: ["Abrelatas", "Guardamentas", "Sacapuntas", "Revolucionario"], correct: 3, procedure: "Revolucionario es simple/derivada." },
    { id: 63, category: "ESTRUCTURA DE LA LENGUA", question: "Ésta, éste, éstos son...", options: ["demostrativos", "preposiciones", "artículos", "personales"], correct: 0, procedure: "Pronombres demostrativos." },
    { id: 64, category: "ESTRUCTURA DE LA LENGUA", question: "Verbo transitivo", options: ["Salió", "Llegó", "Se aplicará examen", "Se tambaleó"], correct: 2, procedure: "Tiene OD." },
    { id: 65, category: "ESTRUCTURA DE LA LENGUA", question: "Superlativo pobre", options: ["Pobrísimo", "Paupérrimo", "Pobretón", "Pobrecito"], correct: 1, procedure: "Paupérrimo." },
    { id: 66, category: "ESTRUCTURA DE LA LENGUA", question: "Participios", options: ["1,3,4", "1,2,3", "2,3,5", "2,4,5"], correct: 0, procedure: "Comido, Pensado, Escrito." },
    { id: 67, category: "ESTRUCTURA DE LA LENGUA", question: "Tiempo compuesto correcto", options: ["1,3,5", "5,4,6", "2,4,6", "1,3,4"], correct: 2, procedure: "He gastado, Habremos terminado..." },
    { id: 68, category: "ESTRUCTURA DE LA LENGUA", question: "Palabras graves", options: ["1,4,7,10", "2,5,9,11", "1,7,9,10", "2,6,8,10"], correct: 0, procedure: "Acento penúltima sílaba." },
    { id: 69, category: "ESTRUCTURA DE LA LENGUA", question: "Homófonas", options: ["nada", "casa-caza", "Luisa", "Día"], correct: 1, procedure: "Sonido igual." },
    { id: 70, category: "ESTRUCTURA DE LA LENGUA", question: "ADEMÁS relación", options: ["Deductivo", "Aditivo", "Explicativo", "Causal"], correct: 1, procedure: "Suma." },
    { id: 71, category: "ESTRUCTURA DE LA LENGUA", question: "Relación párrafos", options: ["Causa", "Yuxtaposición", "Coord", "Subord"], correct: 0, procedure: "Conexión lógica." },
    { id: 72, category: "ESTRUCTURA DE LA LENGUA", question: "A PESAR DE", options: ["adición", "objeción", "subordinación", "yuxta"], correct: 1, procedure: "Oposición." },
    { id: 73, category: "ESTRUCTURA DE LA LENGUA", question: "Oración simple", options: ["Jessica...", "Hermana...", "Amigos...", "Omar entregó"], correct: 3, procedure: "Un verbo." },
    { id: 74, category: "ESTRUCTURA DE LA LENGUA", question: "Argumentación intenta...", options: ["convencer, asimilar, hechos", "demostrar, convencer, ideas", "asimilar...", "contrastar..."], correct: 1, procedure: "Persuasión." },
    { id: 75, category: "ESTRUCTURA DE LA LENGUA", question: "VOLITIVO", options: ["Fugaz", "Miserable", "Voluntario", "Inconsciente"], correct: 2, procedure: "Voluntad." },
    { id: 76, category: "ESTRUCTURA DE LA LENGUA", question: "Copretérito", options: ["hablaría", "había", "hablaba", "habló"], correct: 2, procedure: "-aba." },
    { id: 77, category: "ESTRUCTURA DE LA LENGUA", question: "Sinónimo MÁCULA", options: ["limpieza", "mancha", "atildado", "pulcritud"], correct: 1, procedure: "Mancha." },
    { id: 78, category: "ESTRUCTURA DE LA LENGUA", question: "Antónimo TACITURNO", options: ["Calmado", "Frío", "Ceñudo", "Alegre"], correct: 3, procedure: "Alegre." },
    { id: 79, category: "ESTRUCTURA DE LA LENGUA", question: "Error coherencia", options: ["Pasillo vacío", "Aroma se ve bien", "Me agrada", "Profesor cansado"], correct: 1, procedure: "Aroma no se ve." },
    { id: 80, category: "ESTRUCTURA DE LA LENGUA", question: "Subjuntivo", options: ["Ojalá llegue", "Limpia!", "Cristina escribió", "Carolina estudiará"], correct: 0, procedure: "Deseo/Posibilidad." },
    { id: 81, category: "ESTRUCTURA DE LA LENGUA", question: "Uso coma", options: ["Patty Claudia,", "Pedro, es", "mas, no", "pasas, higos..."], correct: 3, procedure: "Enumeración." },
    { id: 82, category: "ESTRUCTURA DE LA LENGUA", question: "Diptongo/Triptongo lista", options: ["1 y 2...", "1,2,5...", "3 y 5...", "4 y 2..."], correct: 1, procedure: "Fonética." },

    // --- COMPRENSIÓN LECTORA (83-110) ---
    { id: 83, category: "COMPRENSIÓN LECTORA", question: "Frase 'Poco hacer... habladoras'", options: ["Desempleados", "Actúa no pregona", "Piensa habla", "Cuidado"], correct: 1, procedure: "Refrán." },
    { id: 84, category: "COMPRENSIÓN LECTORA", question: "Opinión", options: ["Brasil", "Everest", "No creo Santiago", "México"], correct: 2, procedure: "Subjetivo." },
    { id: 85, category: "COMPRENSIÓN LECTORA", question: "Columnas Estructura Texto", options: ["1B...", "1B...", "1C...", "1D..."], correct: 0, procedure: "Orden lógico." },
    { id: 87, category: "COMPRENSIÓN LECTORA", question: "Idea principal Napoleón", options: ["Familia", "No natural", "Exilio", "Conspiración"], correct: 1, procedure: "Envenenamiento." },
    { id: 88, category: "COMPRENSIÓN LECTORA", question: "Si prueba Marsh existiera antes...", options: ["Napoleón vivo", "Detectado antes", "Evitado riesgo", "No usado pigmento"], correct: 1, procedure: "Detección forense." },
    { id: 89, category: "COMPRENSIÓN LECTORA", question: "Polvo herencia", options: ["Trimetil", "Óxido arsénico", "Arseniato", "Elem"], correct: 1, procedure: "Veneno clásico." },
    { id: 90, category: "COMPRENSIÓN LECTORA", question: "Excepción científico", options: ["Explosión", "Ojos esmeralda", "Estiramiento", "Resonancia"], correct: 1, procedure: "Literario." },
    { id: 91, category: "COMPRENSIÓN LECTORA", question: "Función apelativa", options: ["1,3,4", "3,4,6", "2,3,5", "1,3,6"], correct: 0, procedure: "Instrucciones." },
    { id: 92, category: "COMPRENSIÓN LECTORA", question: "Párrafos con tipo texto", options: ["1B...", "1B...", "1D...", "1C..."], correct: 2, procedure: "Clasificación." },
    { id: 93, category: "COMPRENSIÓN LECTORA", question: "Relaciona lenguaje (Lit, Col, Tec)", options: ["1C...", "1B...", "1B...", "1A..."], correct: 0, procedure: "Nivel lengua." },
    { id: 94, category: "COMPRENSIÓN LECTORA", question: "Saeta voladora mensaje", options: ["Azar", "Playa", "Vida efímera", "Vida sin rumbo"], correct: 3, procedure: "Destino." },
    { id: 95, category: "COMPRENSIÓN LECTORA", question: "Brisa que besa", options: ["Coloquial", "Culto", "Figurado", "Técnico"], correct: 2, procedure: "Metáfora." },
    { id: 96, category: "COMPRENSIÓN LECTORA", question: "Texto argumentos", options: ["Dormí", "Hice tarea porque", "Atmósfera", "Mezcla"], correct: 1, procedure: "Causalidad." },
    { id: 97, category: "COMPRENSIÓN LECTORA", question: "Ordena ALD", options: ["4,1...", "5,6...", "6,1...", "3,5..."], correct: 2, procedure: "Coherencia." },
    { id: 98, category: "COMPRENSIÓN LECTORA", question: "Ordena texto", options: ["1,4...", "6,4...", "6,4...", "4,6..."], correct: 1, procedure: "Coherencia." },
    { id: 99, category: "COMPRENSIÓN LECTORA", question: "Peligrosas aristas", options: ["Heridas", "Curveados", "Sin forma", "Mal cortadas"], correct: 0, procedure: "Filo/Daño." },
    { id: 100, category: "COMPRENSIÓN LECTORA", question: "Quicio", options: ["Pieza", "Locura", "Exasperar", "Hueco"], correct: 2, procedure: "Sacar de quicio." },
    { id: 101, category: "COMPRENSIÓN LECTORA", question: "Cómo quedaron zapatos", options: ["Agujeros/filosos", "Mal cosidos/tacón", "Mal cosidos/incómodos", "Cemento"], correct: 0, procedure: "Descripción lectura." },
    { id: 102, category: "COMPRENSIÓN LECTORA", question: "La ____ texto informativo", options: ["narración", "noticia", "noticia/lírica", "argumentación"], correct: 1, procedure: "Noticia." },
    { id: 103, category: "COMPRENSIÓN LECTORA", question: "Crónica ejemplo", options: ["Mañana martes...", "Magaña anotó...", "Casa Carolina...", "Levantamiento..."], correct: 0, procedure: "Relato temporal." },
    { id: 104, category: "COMPRENSIÓN LECTORA", question: "Causa-efecto excepto", options: ["1", "2", "3", "4"], correct: 3, procedure: "Lógica textual." },
    { id: 105, category: "COMPRENSIÓN LECTORA", question: "Epílogo significado", options: ["Extensión", "Programa", "Conclusión", "Desarrollo"], correct: 2, procedure: "Final." },
    { id: 106, category: "COMPRENSIÓN LECTORA", question: "De la misma manera", options: ["Analogía", "Eliminación", "Adición", "Conclusión"], correct: 0, procedure: "Comparación." },
    { id: 107, category: "COMPRENSIÓN LECTORA", question: "Por lo contrario", options: ["Contrastar", "Homologar", "Reiterar", "Exceptuar"], correct: 0, procedure: "Oposición." },
    { id: 108, category: "COMPRENSIÓN LECTORA", question: "Por consiguiente", options: ["Semejanza", "Contraste", "Comparación", "Causa-consecuencia"], correct: 3, procedure: "Consecuencia." },
    { id: 109, category: "COMPRENSIÓN LECTORA", question: "Conectores ordenadores", options: ["1,2,3", "2,3,5", "3,5,6", "1,4,5"], correct: 3, procedure: "Para terminar, Por otra parte..." },
    { id: 110, category: "COMPRENSIÓN LECTORA", question: "Relación causal ejemplo", options: ["No obstante", "Porque", "Al mismo tiempo", "El más importante"], correct: 1, procedure: "Porque." }
];

// Helper
function getQuestionsByCategory(cat) {
    return quizData.filter(q => q.category === cat);
}
