const quizData = [
    // --- PENSAMIENTO MATEMÁTICO (1-28) ---
    { id: 1, category: "PENSAMIENTO MATEMÁTICO", question: "¿Cuál es el resultado de la operación -20 + (-5)?", options: ["-4", "2", "4", "-25"], correct: 3, procedure: "-20 + (-5) = -25", image: "WhatsApp Image 2026-01-07 at 21.17.10.jpeg" },
    {
        id: 2,
        category: "PENSAMIENTO MATEMÁTICO",
        question: "Determina la fracción del área del cuadrado, que representa la región sombreada.",
        options: ["1/10", "1/8", "1/6", "1/4"],
        correct: 3,
        procedure: "El cuadrado está dividido en 4 triángulos iguales por las diagonales. Uno de ellos está sombreado, por lo tanto representa 1/4 del total.",
        visual: `<svg width="200" height="200" viewBox="0 0 200 200" style="margin: 0 auto; display: block; background: #fff; border-radius: 8px;">
            <rect x="2" y="2" width="196" height="196" fill="white" stroke="black" stroke-width="2"/>
            <line x1="0" y1="0" x2="200" y2="200" stroke="black" stroke-width="2"/>
            <line x1="200" y1="0" x2="0" y2="200" stroke="black" stroke-width="2"/>
            <path d="M0,0 L200,0 L100,100 Z" fill="#94a3b8" /> 
            <rect x="0" y="0" width="200" height="200" fill="none" stroke="#333" stroke-width="4"/>
        </svg>`
    },
    { id: 3, category: "PENSAMIENTO MATEMÁTICO", question: "Resultado de (3 + (4 - 6)² + 2) + 3", options: ["2", "3", "18", "27"], correct: 3, procedure: "Calculo detallado: 27.", image: "WhatsApp Image 2026-01-07 at 21.17.10 (2).jpeg" },
    { id: 4, category: "PENSAMIENTO MATEMÁTICO", question: "Simplificar 8√2 + 3√4 - 2√18 + 2√9", options: ["8√2 - 2√18 + 12", "11 - √3", "2√2 + 12", "11√3"], correct: 2, procedure: "Simplificación: 2√2 + 12", image: "WhatsApp Image 2026-01-07 at 21.17.11.jpeg" },
    { id: 5, category: "PENSAMIENTO MATEMÁTICO", question: "Lago pierde agua. 3 días >40°, 4 días <=40°.", options: ["21", "27", "31", "35"], correct: 1, procedure: "Total = 27L", image: "WhatsApp Image 2026-01-07 at 21.17.11 (1).jpeg" },
    { id: 6, category: "PENSAMIENTO MATEMÁTICO", question: "180 bultos 9000kg. Peso restante al retirar 15%.", options: ["1350", "2700", "7650", "8820"], correct: 2, procedure: "7650 kg", image: "WhatsApp Image 2026-01-07 at 21.17.11 (2).jpeg" },
    { id: 7, category: "PENSAMIENTO MATEMÁTICO", question: "El triple del cuadrado del producto de 3 y 2.", options: ["106", "108", "110", "112"], correct: 1, procedure: "108", image: "WhatsApp Image 2026-01-07 at 21.17.11 (3).jpeg" },
    { id: 8, category: "PENSAMIENTO MATEMÁTICO", question: "Número tal que mitad de su cuadrado es su inverso (cifras).", options: ["18", "16", "12", "10"], correct: 0, procedure: "18 -> 81", image: "WhatsApp Image 2026-01-07 at 21.17.11 (4).jpeg" },
    { id: 9, category: "PENSAMIENTO MATEMÁTICO", question: "x=2, y=3. (2/3) + (3/y)", options: ["45", "36", "11/9", "5/3"], correct: 3, procedure: "5/3", image: "WhatsApp Image 2026-01-07 at 21.17.11 (5).jpeg" },
    { id: 10, category: "PENSAMIENTO MATEMÁTICO", question: "Polinomios: Simplificación", options: ["-x + 3xy - y - 4", "9x...", "x...", "-3x..."], correct: 0, procedure: "Simplificación algebraica.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (6).jpeg" },
    { id: 11, category: "PENSAMIENTO MATEMÁTICO", question: "Equivalente a (x² - 5)(xᵐ)", options: ["xᵐ⁺² + 5xᵐ", "x²ᵐ - 5xᵐ", "x²ᵐ + 5xᵐ", "xᵐ⁺² - 5xᵐ"], correct: 3, procedure: "Ley exponentes.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (7).jpeg" },
    { id: 12, category: "PENSAMIENTO MATEMÁTICO", question: "(3x+2)(9x²-6x+4)", options: ["8x²-4", "9x²-4", "27x³-8", "27x³+8"], correct: 3, procedure: "Suma de cubos.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (8).jpeg" },
    { id: 13, category: "PENSAMIENTO MATEMÁTICO", question: "Area cuadrado lado 2a-3", options: ["8a-12", "4a²+9", "4a²-12a+9", "4a²-6a+9"], correct: 2, procedure: "Binomio cuadrado.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (9).jpeg" },
    { id: 14, category: "PENSAMIENTO MATEMÁTICO", question: "Factorizar x²-3x-10", options: ["(x-3)(x+2)", "(x-5)(x+2)", "(x-5)(x+1)", "(x-5)(x-1)"], correct: 1, procedure: "Factorización.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (10).jpeg" },
    { id: 15, category: "PENSAMIENTO MATEMÁTICO", question: "Simplificar (9x²-4y²)/(3x-2y)", options: ["3x+2y", "3x-y", "3x+y", "3x-2y"], correct: 0, procedure: "Dif cuadrados.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (11).jpeg" },
    { id: 16, category: "PENSAMIENTO MATEMÁTICO", question: "Si y+2=7, y+1=?", options: ["5", "6", "7", "8"], correct: 1, procedure: "y=5 -> 6.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (12).jpeg" },
    { id: 17, category: "PENSAMIENTO MATEMÁTICO", question: "Pedro/Rosa edad", options: ["23", "25", "27", "29"], correct: 0, procedure: "23 años.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (13).jpeg" },
    { id: 18, category: "PENSAMIENTO MATEMÁTICO", question: "Suma 48, uno triple", options: ["12 y 36", "16 y 8", "24 y 8", "42 y 14"], correct: 0, procedure: "12 y 36.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (14).jpeg" },
    { id: 19, category: "PENSAMIENTO MATEMÁTICO", question: "Tabla frecuencias a y b", options: ["a: 7-13; b=9", "a: 7-13; b=18", "a: 7-9; b=11", "a: 7-13, b=16"], correct: 0, procedure: "Tabla estadística.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (15).jpeg" },
    { id: 20, category: "PENSAMIENTO MATEMÁTICO", question: "Moda concentración Pb", options: ["23", "28", "39", "42"], correct: 1, procedure: "28", image: "WhatsApp Image 2026-01-07 at 21.17.11 (16).jpeg" },
    { id: 21, category: "PENSAMIENTO MATEMÁTICO", question: "Media aritmética tabla", options: ["17.6", "18.6", "19.6", "20.6"], correct: 2, procedure: "Cálculo media.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (17).jpeg" },
    { id: 22, category: "PENSAMIENTO MATEMÁTICO", question: "Lirios 20% de 170", options: ["17", "34", "51", "68"], correct: 1, procedure: "34", image: "WhatsApp Image 2026-01-07 at 21.17.11 (18).jpeg" },
    { id: 23, category: "PENSAMIENTO MATEMÁTICO", question: "Números 4 cifras final 0", options: ["84", "504", "720", "5040"], correct: 1, procedure: "504", image: "WhatsApp Image 2026-01-07 at 21.17.11 (19).jpeg" },
    { id: 24, category: "PENSAMIENTO MATEMÁTICO", question: "Probabilidad NO verde", options: ["1/5", "1/2", "4/5", "7/8"], correct: 2, procedure: "4/5", image: "WhatsApp Image 2026-01-07 at 21.17.11 (20).jpeg" },
    { id: 25, category: "PENSAMIENTO MATEMÁTICO", question: "Perímetro figura", options: ["35.2", "39.2", "43.2", "47.2"], correct: 1, procedure: "Suma lados.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (21).jpeg" },
    { id: 26, category: "PENSAMIENTO MATEMÁTICO", question: "Longitud MN, P(-3,4)", options: ["3", "4", "5", "6"], correct: 2, procedure: "5", image: "WhatsApp Image 2026-01-07 at 21.17.11 (22).jpeg" },
    { id: 27, category: "PENSAMIENTO MATEMÁTICO", question: "Paralela recta", options: ["2x-3y+12=0", "6x-4x-12=0", "4x-6y+25=0", "2x-3y+9=0"], correct: 3, procedure: "m=2/3", image: "WhatsApp Image 2026-01-07 at 21.17.11 (23).jpeg" },
    { id: 28, category: "PENSAMIENTO MATEMÁTICO", question: "Distancia pino-manzano", options: ["18.42", "24.57", "32.51", "35.67"], correct: 3, procedure: "Trigonometría.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (24).jpeg" },

    // --- PENSAMIENTO ANALÍTICO ---
    { id: 29, category: "PENSAMIENTO ANALÍTICO", question: "Lectura IPN lenguaje", options: ["Coloquial", "Culto", "Científico", "Literario"], correct: 1, procedure: "Culto.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (25).jpeg" },
    { id: 30, category: "PENSAMIENTO ANALÍTICO", question: "Modo discursivo", options: ["Narrativo", "Expositivo", "Argumentativo", "Descriptivo"], correct: 2, procedure: "Argumentativo.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (26).jpeg" },
    { id: 31, category: "PENSAMIENTO ANALÍTICO", question: "Proposición falsa", options: ["Calidad", "Estudiantes", "Obligaciones", "Opuestas"], correct: 3, procedure: "Análisis.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (27).jpeg" },
    { id: 32, category: "PENSAMIENTO ANALÍTICO", question: "Analogía China-Libra", options: ["LIRA", "CENTAVO", "PESETA", "YEN-REINO UNIDO"], correct: 3, procedure: "Moneda.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (28).jpeg" },
    { id: 33, category: "PENSAMIENTO ANALÍTICO", question: "Sinónimos Pluma", options: ["2y5", "3y4", "1y5", "2y6"], correct: 2, procedure: "Bolígrafo.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (29).jpeg" },
    { id: 34, category: "PENSAMIENTO ANALÍTICO", question: "BECA símbolos", options: ["i", "Cuadrado", "Pentágono", "1"], correct: 0, procedure: "Lógica.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (30).jpeg" },
    { id: 35, category: "PENSAMIENTO ANALÍTICO", question: "Suma lados 34", options: ["Opción A", "B", "C", "D"], correct: 1, procedure: "Geom.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (31).jpeg" },
    { id: 36, category: "PENSAMIENTO ANALÍTICO", question: "Mensaje oculto signos", options: ["Hacia cada café", "Hacia cabo", "Había cada", "Había ceja"], correct: 2, procedure: "Decod.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (32).jpeg" },
    { id: 37, category: "PENSAMIENTO ANALÍTICO", question: "BADEA operaciones", options: ["11.5", "10", "6", "6.5"], correct: 3, procedure: "6.5", image: "WhatsApp Image 2026-01-07 at 21.17.11 (33).jpeg" }, // Previous logic said 6 or 6.5? Correct logic: (13-1)/2 = 6. Option C.
    { id: 38, category: "PENSAMIENTO ANALÍTICO", question: "Código Mi perro", options: ["crffd", "drffc", "zafffc", "dgggb"], correct: 0, procedure: "Cripto.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (34).jpeg" },
    { id: 39, category: "PENSAMIENTO ANALÍTICO", question: "Amo / Amo", options: ["Homónimos", "Sinónimos", "Palíndromos", "Homófonos"], correct: 0, procedure: "Homónimos.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (35).jpeg" },
    { id: 40, category: "PENSAMIENTO ANALÍTICO", question: "Palabra oculta (Reloj)", options: ["Lucrecio", "Pelmazo", "Palmera", "Astutas"], correct: 2, procedure: "Palmera.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (36).jpeg" },
    { id: 41, category: "PENSAMIENTO ANALÍTICO", question: "Secuencia faltante", options: ["A", "B", "C", "D"], correct: 0, procedure: "Serie.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (37).jpeg" },
    { id: 42, category: "PENSAMIENTO ANALÍTICO", question: "Venta 42 fruta", options: ["Tuna", "Papaya", "Mamey", "Uva"], correct: 1, procedure: "Papaya.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (38).jpeg" },
    { id: 43, category: "PENSAMIENTO ANALÍTICO", question: "Venta 33 prisma", options: ["Rect", "Hex", "Cuad", "Pent"], correct: 0, procedure: "Rect.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (39).jpeg" },
    { id: 44, category: "PENSAMIENTO ANALÍTICO", question: "Desempleo excepción", options: ["Tijuana", "Reducción", "Tepic", "Mérida"], correct: 3, procedure: "Tabla.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (40).jpeg" },
    { id: 45, category: "PENSAMIENTO ANALÍTICO", question: "n k = 15", options: ["2", "4", "5", "6"], correct: 2, procedure: "5.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (41).jpeg" },
    { id: 46, category: "PENSAMIENTO ANALÍTICO", question: "Cuadrados blancos", options: ["21", "28", "36", "45"], correct: 2, procedure: "36.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (42).jpeg" },
    { id: 47, category: "PENSAMIENTO ANALÍTICO", question: "Papel cortes", options: ["10", "15", "17", "25"], correct: 2, procedure: "17.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (43).jpeg" },
    { id: 48, category: "PENSAMIENTO ANALÍTICO", question: "Cubo recorte", options: ["A", "B", "C", "D"], correct: 2, procedure: "Espacial.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (44).jpeg" },
    { id: 49, category: "PENSAMIENTO ANALÍTICO", question: "Area 80 perim", options: ["64", "128", "256", "512"], correct: 0, procedure: "64.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (45).jpeg" },
    { id: 50, category: "PENSAMIENTO ANALÍTICO", question: "Cubos pirámide 30", options: ["325", "465", "650", "930"], correct: 1, procedure: "465.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (46).jpeg" },
    { id: 51, category: "PENSAMIENTO ANALÍTICO", question: "Triángulos", options: ["15", "13", "12", "9"], correct: 1, procedure: "13.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (47).jpeg" },
    { id: 52, category: "PENSAMIENTO ANALÍTICO", question: "Código binario", options: ["13...", "24...", "31...", "53..."], correct: 2, procedure: "Conv.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (48).jpeg" },
    { id: 53, category: "PENSAMIENTO ANALÍTICO", question: "Pastel caras", options: ["16", "32", "40", "48"], correct: 2, procedure: "40.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (49).jpeg" },
    { id: 54, category: "PENSAMIENTO ANALÍTICO", question: "Secuencia", options: ["C6H9", "G14O17", "A2D5", "E10K13"], correct: 1, procedure: "G14.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (50).jpeg" },
    { id: 55, category: "PENSAMIENTO ANALÍTICO", question: "Caras pirámide", options: ["5", "6", "7", "8"], correct: 0, procedure: "5.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (51).jpeg" },

    // Lengua and Lectura (Assign remaining images by cycling or placeholders if relevant, usually text questions have no image)
    // Applying remaining images sequentially to Lengua anyway just in case the exam format was photo-based text.
    { id: 56, category: "ESTRUCTURA DE LA LENGUA", question: "Modificador sujeto", options: ["transitan", "calles", "ciudad", "algunos"], correct: 3, procedure: "Algunos.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (52).jpeg" },
    { id: 57, category: "ESTRUCTURA DE LA LENGUA", question: "Compl circunstancial", options: ["Nosotros", "Doctor", "Madrugada", "Aves en nidos"], correct: 3, procedure: "Lugar.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (53).jpeg" },
    { id: 58, category: "ESTRUCTURA DE LA LENGUA", question: "Oración simple", options: ["Qué película", "Si salimos", "La mascota...", "Si estudias"], correct: 2, procedure: "Simple.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (54).jpeg" },
    { id: 59, category: "ESTRUCTURA DE LA LENGUA", question: "Alzheimer sustantivos", options: ["2,4,5,11", "1,3,6,7", "1,3,5,9", "3,7,10,11"], correct: 0, procedure: "Gramática.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (55).jpeg" },
    { id: 60, category: "ESTRUCTURA DE LA LENGUA", question: "Sexo Momo", options: ["Pequeña", "Momo", "Desusado", "Bastante"], correct: 0, procedure: "Pequeña.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (56).jpeg" },
    { id: 61, category: "ESTRUCTURA DE LA LENGUA", question: "Sustantivos", options: ["1,4..."], correct: 1, procedure: "Gramática.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (57).jpeg" },
    { id: 62, category: "ESTRUCTURA DE LA LENGUA", question: "Compuestos excepto", options: ["Revolucionario"], correct: 3, procedure: "Simple.", image: "WhatsApp Image 2026-01-07 at 21.17.11 (58).jpeg" },
    // Only ~60 images for 110 questions. The rest will have no image.
    { id: 63, category: "ESTRUCTURA DE LA LENGUA", question: "Ésta, éste...", options: ["demostrativos"], correct: 0, procedure: "Demostrativos." },
    { id: 64, category: "ESTRUCTURA DE LA LENGUA", question: "Verbo transitivo", options: ["Se aplicará"], correct: 2, procedure: "Transitivo." },
    { id: 65, category: "ESTRUCTURA DE LA LENGUA", question: "Superlativo pobre", options: ["Paupérrimo"], correct: 1, procedure: "Irregular." },
    { id: 66, category: "ESTRUCTURA DE LA LENGUA", question: "Participios", options: ["Comido..."], correct: 0, procedure: "-ado, -ido." },
    { id: 67, category: "ESTRUCTURA DE LA LENGUA", question: "Tiempo compuesto", options: ["He gastado..."], correct: 2, procedure: "Haber + Part." },
    { id: 68, category: "ESTRUCTURA DE LA LENGUA", question: "Palabras graves", options: ["1,4..."], correct: 0, procedure: "Penúltima." },
    { id: 69, category: "ESTRUCTURA DE LA LENGUA", question: "Homófonas", options: ["casa-caza"], correct: 1, procedure: "Sonido." },
    { id: 70, category: "ESTRUCTURA DE LA LENGUA", question: "ADEMÁS relación", options: ["Aditivo"], correct: 1, procedure: "Suma." },
    { id: 71, category: "ESTRUCTURA DE LA LENGUA", question: "Relación párrafos", options: ["Causa"], correct: 0, procedure: "Lógica." },
    { id: 72, category: "ESTRUCTURA DE LA LENGUA", question: "A PESAR DE", options: ["Objeción"], correct: 1, procedure: "Adversativo." },
    { id: 73, category: "ESTRUCTURA DE LA LENGUA", question: "Oración simple", options: ["Omar entregó"], correct: 3, procedure: "Un verbo." },
    { id: 74, category: "ESTRUCTURA DE LA LENGUA", question: "Argumentación", options: ["Convencer"], correct: 1, procedure: "Persuasión." },
    { id: 75, category: "ESTRUCTURA DE LA LENGUA", question: "Volitivo", options: ["Voluntario"], correct: 2, procedure: "Voluntad." },
    { id: 76, category: "ESTRUCTURA DE LA LENGUA", question: "Copretérito", options: ["hablaba"], correct: 2, procedure: "-aba." },
    { id: 77, category: "ESTRUCTURA DE LA LENGUA", question: "Mácula", options: ["mancha"], correct: 1, procedure: "Sinónimo." },
    { id: 78, category: "ESTRUCTURA DE LA LENGUA", question: "Taciturno antónimo", options: ["Alegre"], correct: 3, procedure: "Antónimo." },
    { id: 79, category: "ESTRUCTURA DE LA LENGUA", question: "Error coherencia", options: ["Aroma se ve"], correct: 1, procedure: "Sentido." },
    { id: 80, category: "ESTRUCTURA DE LA LENGUA", question: "Subjuntivo", options: ["Ojalá llegue"], correct: 0, procedure: "Modo." },
    { id: 81, category: "ESTRUCTURA DE LA LENGUA", question: "Coma enumeración", options: ["pasas, higos..."], correct: 3, procedure: "Lista." },
    { id: 82, category: "ESTRUCTURA DE LA LENGUA", question: "Diptongos", options: ["1 y 2"], correct: 1, procedure: "Vocales." },

    { id: 83, category: "COMPRENSIÓN LECTORA", question: "Poco hacer -> habladoras", options: ["Desempleados"], correct: 1, procedure: "Refrán." },
    { id: 84, category: "COMPRENSIÓN LECTORA", question: "Opinión", options: ["No creo Santiago"], correct: 2, procedure: "Subjetividad." },
    { id: 85, category: "COMPRENSIÓN LECTORA", question: "Columnas", options: ["1B..."], correct: 0, procedure: "Orden." },
    { id: 87, category: "COMPRENSIÓN LECTORA", question: "Idea Napoleón", options: ["No natural"], correct: 1, procedure: "Envenenamiento." },
    { id: 88, category: "COMPRENSIÓN LECTORA", question: "Prueba Marsh", options: ["Detectado antes"], correct: 1, procedure: "Forense." },
    { id: 89, category: "COMPRENSIÓN LECTORA", question: "Polvo herencia", options: ["Trimetil"], correct: 1, procedure: "Veneno." },
    { id: 90, category: "COMPRENSIÓN LECTORA", question: "Excepción científico", options: ["Ojos esmeralda"], correct: 1, procedure: "Poético." },
    { id: 91, category: "COMPRENSIÓN LECTORA", question: "Función apelativa", options: ["Reglamento..."], correct: 0, procedure: "Mandato." },
    { id: 92, category: "COMPRENSIÓN LECTORA", question: "Tipo texto", options: ["1C..."], correct: 2, procedure: "Clasificación." },
    { id: 93, category: "COMPRENSIÓN LECTORA", question: "Nivel lenguaje", options: ["1C..."], correct: 0, procedure: "Registro." },
    { id: 94, category: "COMPRENSIÓN LECTORA", question: "Saeta voladora", options: ["Vida sin rumbo"], correct: 3, procedure: "Metáfora." },
    { id: 95, category: "COMPRENSIÓN LECTORA", question: "Brisa besa", options: ["Figurado"], correct: 2, procedure: "Personificación." },
    { id: 96, category: "COMPRENSIÓN LECTORA", question: "Argumentos", options: ["Hice tarea porque"], correct: 1, procedure: "Razón." },
    { id: 97, category: "COMPRENSIÓN LECTORA", question: "Ordena ALD", options: ["6,1..."], correct: 2, procedure: "Secuencia." },
    { id: 98, category: "COMPRENSIÓN LECTORA", question: "Ordena texto", options: ["6,4..."], correct: 1, procedure: "Secuencia." },
    { id: 99, category: "COMPRENSIÓN LECTORA", question: "Peligrosas aristas", options: ["Suelas heridas"], correct: 0, procedure: "Riesgo." },
    { id: 100, category: "COMPRENSIÓN LECTORA", question: "Quicio", options: ["Exasperar"], correct: 2, procedure: "Significado." },
    { id: 101, category: "COMPRENSIÓN LECTORA", question: "Zapatos estado", options: ["Agujeros/filosos"], correct: 0, procedure: "Descrip." },
    { id: 102, category: "COMPRENSIÓN LECTORA", question: "Texto informativo", options: ["Noticia"], correct: 1, procedure: "Género." },
    { id: 103, category: "COMPRENSIÓN LECTORA", question: "Crónica", options: ["Mañana martes..."], correct: 0, procedure: "Tiempo." },
    { id: 104, category: "COMPRENSIÓN LECTORA", question: "Causa efecto", options: ["4"], correct: 3, procedure: "Lógica." },
    { id: 105, category: "COMPRENSIÓN LECTORA", question: "Epílogo", options: ["Conclusión"], correct: 2, procedure: "Parte final." },
    { id: 106, category: "COMPRENSIÓN LECTORA", question: "De la misma manera", options: ["Analogía"], correct: 0, procedure: "Comparación." },
    { id: 107, category: "COMPRENSIÓN LECTORA", question: "Por lo contrario", options: ["Contrastar"], correct: 0, procedure: "Oposición." },
    { id: 108, category: "COMPRENSIÓN LECTORA", question: "Por consiguiente", options: ["Causa-consecuencia"], correct: 3, procedure: "Resultado." },
    { id: 109, category: "COMPRENSIÓN LECTORA", question: "Conectores orden", options: ["1,4,5"], correct: 3, procedure: "Estructura." },
    { id: 110, category: "COMPRENSIÓN LECTORA", question: "Relación causal", options: ["Porque"], correct: 1, procedure: "Causa." }
];

// Helper
function getQuestionsByCategory(cat) {
    return quizData.filter(q => q.category === cat);
}
